apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafkasource
  namespace: my-namespace
spec:
  consumerGroup: demo-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - kafkasource-demo
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sink
