apiVersion: batch/v1
kind: Job
metadata:
  name: message-generator
  namespace: my-namespace
spec:
  template:
    spec:
      containers:
        - name: message-generator
          image: docker.io/aliok/message-generator:latest
          env:
            - name: KAFKA_HOST
              value: my-cluster-kafka-bootstrap.kafka:9092
            - name: KAFKA_TOPIC
              value: kafkasource-demo
            - name: MESSAGE_COUNT
              value: '20000'
            - name: MESSAGE_FREQUENCY
              value: '0'
      restartPolicy: Never
